version: "3.7"

services:
  app:
    image: ghcr.io/chyroc/greader:latest
    ports:
      - "8081:8081"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: your-password
      MYSQL_DATABASE: greader
      restart: always
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: your-password
      MYSQL_DATABASE: greader
    volumes:
      - "./mysql_backend/sql/all.sql:/docker-entrypoint-initdb.d/all.sql"
    restart: always
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        interval: 10s
        timeout: 5s
        retries: 5